# add dvc stages here 
stages:
  prepare_data:
    cmd: python src/stage_1_prep_data.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_1_prep_data.py
      - data/data.xml
      - src/utils/common.py
      - src/utils/data_management.py
      - configs/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize_data:
    cmd: python src/stage_2_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_2_featurization.py
      - src/utils/common.py
      - src/utils/featurize.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - configs/config.yaml
    params:
      - featurize.max_params
      - featurize.n_grams
    outs:
      - artifacts/feature/train.pkl
      - artifacts/feature/test.pkl

  train:
    cmd: python src/stage_3_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_3_train.py
      - src/utils/common.py
      - artifacts/feature/train.pkl
      - configs/config.yaml
    params:
      - train.min_split
      - train.n_est
      - train.seed
    outs:
      - artifacts/model/model.pkl
  
  evaluate:
    cmd: python src/stage_4_evaluate.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_4_evaluate.py
      - src/utils/common.py
      - artifacts/feature/test.pkl
      - configs/config.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots: 
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  run_plots_command:
    cmd: dvc plots diff



  

  
