# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_1_prep_data.py
    deps:
      - src/stage_1_prep_data.py
      - data/data.xml
      - src/utils/common.py
      - src/utils/data_management.py
      - configs/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

